//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE
    {
        public SITE()
        {
            this.COMMENTS = new HashSet<COMMENTS>();
            this.IMAGE = new HashSet<IMAGE>();
            this.VOTE = new HashSet<VOTE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string InsertDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Active { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
    
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        public virtual ICollection<IMAGE> IMAGE { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual ICollection<VOTE> VOTE { get; set; }
    }
}
