//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.SITE = new HashSet<SITE>();
        }
    
        public int ID { get; set; }
        public int GroupID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
        public string Job { get; set; }
        public string Gsm { get; set; }
        public string Birthday { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Block { get; set; }
    
        public virtual ICollection<SITE> SITE { get; set; }
    }
}
