//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using Container;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBHOUSEEntities : DbContext
    {
        public WEBHOUSEEntities()
            : base("name=WEBHOUSEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORY> CATEGORY { get; set; }
        public DbSet<COMMENTS> COMMENTS { get; set; }
        public DbSet<IMAGE> IMAGE { get; set; }
        public DbSet<SITE> SITE { get; set; }
        public DbSet<SUB_CATEGORY> SUB_CATEGORY { get; set; }
        //public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USER_GROUPS> USER_GROUPS { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<VOTE> VOTE { get; set; }
    }
}
